kind: pipeline
name: default

steps:
- name: publish  
  image: plugins/gcr
  settings:
    registry: us.gcr.io
    repo: marwanio-192300/moddoc
    tags:
      - latest
    json_key:
      from_secret: google_credentials
  when:
    branch:
      - master
    event:
      - push
