kind: pipeline
name: default

steps:
- name: build
  image: golang:1.12
  commands:
    - go test ./...
  environment:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on
  when:
    branch:
      - master
    event:
      - push
      - pull_request

- name: publish  
  image: plugins/gcr
  settings:
    registry: us.gcr.io
    repo: marwanio-192300/moddoc
    tags:
      - latest
    json_key:
      from_secret: google_credentials
  when:
    branch:
      - master
    event:
      - push
